"""Data management page: upload, retrain, compare, accept/reject."""
import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

from utils.data_loader import load_metrics

# Load local OAuth credentials if present
load_dotenv()

ROOT = Path(__file__).resolve().parents[2]
MODELS_DIR = ROOT / "app" / "models"
OUTPUTS_DIR = ROOT / "app" / "outputs" / "forecasts"
DATA_DIR = ROOT / "app" / "data"

# Ensure repo root is in path for dynamic imports inside functions
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _find_newest_artifacts():
    """Find the newest model/metrics/validation generated by the pipeline."""
    metrics_files = sorted(MODELS_DIR.glob("metrics_20*.json"))
    models_files = sorted(MODELS_DIR.glob("hourly_lgbm_20*.pkl"))
    val_files = sorted(OUTPUTS_DIR.glob("validation_20*.csv"))
    parquet_files = sorted(DATA_DIR.glob("hourly_features_20*.parquet"))

    if not metrics_files or not models_files:
        return None

    metrics_path = metrics_files[-1]
    model_path = models_files[-1]
    val_path = val_files[-1] if val_files else None
    parquet_path = parquet_files[-1] if parquet_files else None

    timestamp = metrics_path.stem.replace("metrics_", "")

    with open(metrics_path, "r") as f:
        metrics = json.load(f)

    return {
        "timestamp": timestamp,
        "metrics": metrics,
        "model_path": model_path,
        "metrics_path": metrics_path,
        "val_path": val_path,
        "parquet_path": parquet_path,
    }


def _load_current_metrics():
    """Load currently active model metrics."""
    path = MODELS_DIR / "metrics_hourly.json"
    if path.exists():
        with open(path, "r") as f:
            return json.load(f)
    return None


def _activate_new_model(artifacts):
    """Copy timestamped artifacts to active filenames."""
    backup_ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    for src, dst in [
        (MODELS_DIR / "hourly_lgbm.pkl", MODELS_DIR / f"hourly_lgbm_backup_{backup_ts}.pkl"),
        (MODELS_DIR / "metrics_hourly.json", MODELS_DIR / f"metrics_backup_{backup_ts}.json"),
        (OUTPUTS_DIR / "validation_hourly.csv", OUTPUTS_DIR / f"validation_backup_{backup_ts}.csv"),
        (DATA_DIR / "hourly_features.parquet", DATA_DIR / f"hourly_features_backup_{backup_ts}.parquet"),
    ]:
        if src.exists():
            shutil.copy2(src, dst)

    shutil.copy2(artifacts["model_path"], MODELS_DIR / "hourly_lgbm.pkl")
    shutil.copy2(artifacts["metrics_path"], MODELS_DIR / "metrics_hourly.json")

    if artifacts["val_path"]:
        shutil.copy2(artifacts["val_path"], OUTPUTS_DIR / "validation_hourly.csv")

    if artifacts["parquet_path"]:
        shutil.copy2(artifacts["parquet_path"], DATA_DIR / "hourly_features.parquet")

    return True


def _upload_to_drive_pending(temp_path: Path):
    """Upload validated file to Drive raw/pending/ and return success status."""
    try:
        from app.api.drive_client import (
            get_drive_service,
            get_or_create_folder,
            find_folder,
            upload_file,
        )
        service = get_drive_service()
        gcc_id = find_folder(service, "GCC_Corp")
        if not gcc_id:
            raise FileNotFoundError("GCC_Corp folder not found in Drive")
        raw_id = get_or_create_folder(service, "raw", parent_id=gcc_id)
        pending_id = get_or_create_folder(service, "pending", parent_id=raw_id)
        upload_file(service, temp_path, parent_id=pending_id)
        return True
    except Exception as e:
        st.error(f"Error al subir a Drive: {e}")
        return False


def _delete_artifacts(artifacts):
    """Delete timestamped artifacts (user rejected them)."""
    for path in [artifacts["model_path"], artifacts["metrics_path"],
                 artifacts["val_path"], artifacts["parquet_path"]]:
        if path and path.exists():
            path.unlink()


def show_data_management_page():
    st.title("Reentrenamiento de Modelo")
    st.caption("C.O.R.P. v2 - Reentrenamiento y validacion")

    # ------------------------------------------------------------------
    # Section 1: Upload new data
    # ------------------------------------------------------------------
    st.header("Subir Nuevos Datos")
    uploaded = st.file_uploader(
        "Sube un archivo Excel (.xlsx) con remisiones actualizadas",
        type=["xlsx"],
    )

    if uploaded is not None:
        temp_path = Path("/tmp") / uploaded.name
        with open(temp_path, "wb") as f:
            f.write(uploaded.getvalue())

        try:
            sys.path.insert(0, str(ROOT / "app" / "scripts"))
            from validate import validate_new_data
            result = validate_new_data(temp_path)
            st.success(
                f"Validacion exitosa: {result['rows']:,} filas, "
                f"plantas: {result['plants']}, "
                f"filas con nulos eliminadas: {result['null_rows_removed']}"
            )

            df_preview = pd.read_excel(temp_path).head(10)
            st.write("Vista previa:")
            st.dataframe(df_preview, use_container_width=True)

            col_local, col_drive = st.columns(2)

            with col_local:
                if st.button("Entrenar local (desarrollo)", use_container_width=True, key="train_local"):
                    with st.spinner("Entrenando modelo local... (esto puede tardar 3-5 minutos)"):
                        pipeline_script = ROOT / "app" / "scripts" / "run_pipeline.py"

                        result = subprocess.run(
                            [sys.executable, str(pipeline_script), "--new-data", str(temp_path)],
                            capture_output=True,
                            text=True,
                            cwd=str(ROOT),
                        )

                        if result.returncode != 0:
                            st.error("Error durante el entrenamiento local:")
                            st.code(result.stderr or result.stdout)
                        else:
                            st.success("Entrenamiento local completado.")
                            with st.expander("Ver logs"):
                                st.code(result.stdout)
                            st.session_state["show_comparison"] = True
                            st.rerun()

            with col_drive:
                if st.button("Subir a Drive y entrenar", use_container_width=True, key="train_drive", type="primary"):
                    with st.spinner("Subiendo a Drive y entrenando... (esto puede tardar 3-5 minutos)"):
                        # 1. Upload to Drive raw/pending/
                        uploaded_ok = _upload_to_drive_pending(temp_path)
                        if not uploaded_ok:
                            st.error("No se pudo subir el archivo a Drive. Revisa las credenciales.")
                            st.stop()

                        # 2. Run pipeline in Drive mode
                        pipeline_script = ROOT / "app" / "scripts" / "run_pipeline.py"
                        result = subprocess.run(
                            [sys.executable, str(pipeline_script), "--use-drive"],
                            capture_output=True,
                            text=True,
                            cwd=str(ROOT),
                        )

                        if result.returncode != 0:
                            st.error("Error durante el entrenamiento en Drive:")
                            st.code(result.stderr or result.stdout)
                        else:
                            st.success("Entrenamiento en Drive completado. Revisa la comparacion de metricas.")
                            with st.expander("Ver logs"):
                                st.code(result.stdout)
                            st.session_state["show_comparison"] = True
                            st.rerun()

        except Exception as e:
            st.error(f"Error de validacion: {e}")

    st.markdown("---")

    # ------------------------------------------------------------------
    # Section 2: Metrics comparison (Drive integration)
    # ------------------------------------------------------------------
    current = _load_current_metrics()

    # Try to detect pending model from Drive
    drive_pending = None
    drive_error = None
    try:
        from app.utils.drive_sync import get_drive_pending_metrics
        drive_pending = get_drive_pending_metrics()
    except Exception as e:
        drive_error = str(e)

    # Also check for local artifacts (fallback / manual training)
    local_artifacts = _find_newest_artifacts()
    show_local = st.session_state.get("show_comparison", False) or local_artifacts is not None

    # --- DRIVE COMPARISON ---
    if drive_pending and current:
        st.header("Comparacion de Metricas (Drive)")

        col1, col2, col3 = st.columns(3)

        col1.metric("MAE (actual)", f"{current['mae_hourly_m3']:.2f}")
        col1.metric("RMSE (actual)", f"{current['rmse_hourly_m3']:.2f}")

        new_mae = drive_pending["mae_hourly_m3"]
        old_mae = current["mae_hourly_m3"]
        delta_mae = new_mae - old_mae

        new_rmse = drive_pending["rmse_hourly_m3"]
        old_rmse = current["rmse_hourly_m3"]
        delta_rmse = new_rmse - old_rmse

        col2.metric("MAE (nuevo)", f"{new_mae:.2f}", f"{delta_mae:+.2f}", delta_color="inverse")
        col2.metric("RMSE (nuevo)", f"{new_rmse:.2f}", f"{delta_rmse:+.2f}", delta_color="inverse")

        col3.write("**Evaluacion**")
        if new_mae < old_mae:
            col3.success("MAE MEJORO")
        else:
            col3.error("MAE EMPEORO")

        if new_rmse < old_rmse:
            col3.success("RMSE MEJORO")
        else:
            col3.error("RMSE EMPEORO")

        st.markdown("---")

        c1, c2 = st.columns(2)

        with c1:
            if st.button("Mantener modelo actual", use_container_width=True, key="reject_drive"):
                try:
                    from app.utils.drive_sync import reject_drive_model
                    reject_drive_model()
                    st.success("Modelo actual mantenido. Pendiente eliminado de Drive.")
                except Exception as e:
                    st.error(f"Error al rechazar en Drive: {e}")
                st.rerun()

        with c2:
            if st.button("Usar nuevo modelo", use_container_width=True, key="accept_drive"):
                try:
                    from app.utils.drive_sync import approve_drive_model, download_drive_current_to_local
                    approve_drive_model()
                    download_drive_current_to_local()
                    st.success("Nuevo modelo activado en Drive y descargado localmente.")
                except Exception as e:
                    st.error(f"Error al aprobar en Drive: {e}")
                st.rerun()

    # --- LOCAL COMPARISON (fallback) ---
    elif show_local and local_artifacts and current:
        st.header("Comparacion de Metricas (Local)")

        col1, col2, col3 = st.columns(3)

        col1.metric("MAE (actual)", f"{current['mae_hourly_m3']:.2f}")
        col1.metric("RMSE (actual)", f"{current['rmse_hourly_m3']:.2f}")

        new_mae = local_artifacts["metrics"]["mae_hourly_m3"]
        old_mae = current["mae_hourly_m3"]
        delta_mae = new_mae - old_mae

        new_rmse = local_artifacts["metrics"]["rmse_hourly_m3"]
        old_rmse = current["rmse_hourly_m3"]
        delta_rmse = new_rmse - old_rmse

        col2.metric("MAE (nuevo)", f"{new_mae:.2f}", f"{delta_mae:+.2f}", delta_color="inverse")
        col2.metric("RMSE (nuevo)", f"{new_rmse:.2f}", f"{delta_rmse:+.2f}", delta_color="inverse")

        col3.write("**Evaluacion**")
        if new_mae < old_mae:
            col3.success("MAE MEJORO")
        else:
            col3.error("MAE EMPEORO")

        if new_rmse < old_rmse:
            col3.success("RMSE MEJORO")
        else:
            col3.error("RMSE EMPEORO")

        st.markdown("---")

        c1, c2 = st.columns(2)

        with c1:
            if st.button("Mantener modelo actual", use_container_width=True, key="reject_local"):
                _delete_artifacts(local_artifacts)
                st.session_state["show_comparison"] = False
                st.success("Modelo actual mantenido. Archivos de prueba eliminados.")
                st.rerun()

        with c2:
            if st.button("Usar nuevo modelo", use_container_width=True, key="accept_local"):
                _activate_new_model(local_artifacts)
                st.session_state["show_comparison"] = False
                st.success("Nuevo modelo activado. Reinicia la app para usarlo.")
                st.rerun()

    # --- NO PENDING ---
    elif drive_error:
        with st.expander("Drive no disponible"):
            st.caption(drive_error)
            st.info("Crea un archivo .env con GCP_CLIENT_ID, GCP_CLIENT_SECRET y GCP_REFRESH_TOKEN para habilitar la sincronizacion con Drive.")

    # ------------------------------------------------------------------
    # Section 3: Current model training date
    # ------------------------------------------------------------------
    st.markdown("---")
    if current:
        train_date = current.get("date_calculated", "N/A")
        if isinstance(train_date, str) and "T" in train_date:
            train_date = train_date.split("T")[0]
        st.caption(f"Modelo activo entrenado el {train_date}")
    else:
        st.warning("No hay metricas del modelo actual.")
